/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SwingUI;

import com.toedter.calendar.JDateChooser;
import java.awt.Image;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Admin
 */
public class CreateEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateEmployeeJPanel
     */
    
    EmployeeData empData;
    String imagePath;
    static ArrayList<EmployeeData> empDataObjs = new ArrayList<>();
    public CreateEmployeeJPanel() {
        initComponents();
        this.empData=empData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        createEmployeePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        empIDLabel = new javax.swing.JLabel();
        employeeIDText = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageText = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        maleInput = new javax.swing.JRadioButton();
        femaleInput = new javax.swing.JRadioButton();
        otherInput = new javax.swing.JRadioButton();
        startDateLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        teamInfoText = new javax.swing.JTextField();
        positionTitle = new javax.swing.JLabel();
        ptText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cellPhoneText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailID = new javax.swing.JLabel();
        emailIDText = new javax.swing.JTextField();
        photoLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        uploadPhoto = new javax.swing.JButton();
        photoArea = new javax.swing.JLabel();
        jStartDate = new com.toedter.calendar.JDateChooser();
        levelText = new javax.swing.JTextField();

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Employee Details");

        nameLabel.setText("Name");

        empIDLabel.setText("Employee ID");

        ageLabel.setText("Age");

        genderLabel.setText("Gender");

        genderGroup.add(maleInput);
        maleInput.setText("Male");

        genderGroup.add(femaleInput);
        femaleInput.setText("Female");

        genderGroup.add(otherInput);
        otherInput.setText("Other");

        startDateLabel.setText("Start Date");

        jLabel4.setText("Level");

        jLabel5.setText("Team Info");

        positionTitle.setText("Position Title");

        jLabel6.setText("Contact Info");

        jLabel7.setText("Cell Phone");

        emailID.setText("Email ID");

        photoLabel.setText("Photo");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        uploadPhoto.setText("Upload Photo");
        uploadPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadPhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createEmployeePanelLayout = new javax.swing.GroupLayout(createEmployeePanel);
        createEmployeePanel.setLayout(createEmployeePanelLayout);
        createEmployeePanelLayout.setHorizontalGroup(
            createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createEmployeePanelLayout.createSequentialGroup()
                        .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(createEmployeePanelLayout.createSequentialGroup()
                                .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createEmployeePanelLayout.createSequentialGroup()
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(employeeIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(createEmployeePanelLayout.createSequentialGroup()
                        .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createEmployeePanelLayout.createSequentialGroup()
                                .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(startDateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(genderLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(empIDLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(createEmployeePanelLayout.createSequentialGroup()
                                        .addComponent(maleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(femaleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(createEmployeePanelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ptText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(teamInfoText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(levelText, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(createEmployeePanelLayout.createSequentialGroup()
                                .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(positionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(photoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(createEmployeePanelLayout.createSequentialGroup()
                                        .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cellPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(uploadPhoto)
                                    .addComponent(addButton))))
                        .addGap(0, 172, Short.MAX_VALUE))))
            .addGroup(createEmployeePanelLayout.createSequentialGroup()
                .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createEmployeePanelLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(otherInput, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createEmployeePanelLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createEmployeePanelLayout.setVerticalGroup(
            createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createEmployeePanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empIDLabel)
                    .addComponent(employeeIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderLabel)
                    .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maleInput)
                        .addComponent(femaleInput)))
                .addGap(12, 12, 12)
                .addComponent(otherInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createEmployeePanelLayout.createSequentialGroup()
                        .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(levelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(teamInfoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(positionTitle)
                            .addComponent(ptText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cellPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailID)
                    .addComponent(emailIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(createEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createEmployeePanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(photoLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createEmployeePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(photoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(uploadPhoto)
                .addGap(41, 41, 41)
                .addComponent(addButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(createEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(createEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 21, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 21, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        
        String eName=nameText.getText();
        String eID=employeeIDText.getText();
        int age=Integer.parseInt(ageText.getText());
        maleInput.setActionCommand("Male");
        femaleInput.setActionCommand("Female");
        otherInput.setActionCommand("Other");
        String empGender=genderGroup.getSelection().getActionCommand();
        //JDateChooser formatDate=new JDateChooser();
        //formatDate.format(jStartDate.getDate());
        DateFormat formatDate = new SimpleDateFormat("MM-dd-yyy");  
        String startDate = formatDate.format(jStartDate.getDate());
        String empLevel= levelText.getText();
        String empTeamInfo= teamInfoText.getText();
        String empPT= ptText.getText();
        String empPhone=cellPhoneText.getText();
        String empEmail=emailIDText.getText();
        
        
        if(eName.isEmpty() || eID.isEmpty() || ageText.getText().equals("") || empGender.isEmpty()|| startDate.isEmpty()||
                empLevel.isEmpty()|| empTeamInfo.isEmpty()||empPT.isEmpty() || empPhone.isEmpty() || empEmail.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter all the fields", "Missing Details", JOptionPane.ERROR_MESSAGE);
        }if(!eName.matches("^[A-Z][a-z]+[ ]*[A-Za-z]*$")){
                JOptionPane.showMessageDialog(this,
                        "Please Enter Valid Name",
                        "Invalid Name", 
                        JOptionPane.ERROR_MESSAGE);
        }if(empPhone.length()!= 10 && !empPhone.matches("\\+\\d(-\\d{3}){2}-\\d{4}")){
                JOptionPane.showMessageDialog(this,
                        "Please Enter Valid Phone Number",
                        "Invalid Phone Number", 
                        JOptionPane.ERROR_MESSAGE);
        }if(!empEmail.matches("^[a-z0-9]+@[a-z]+\\.[a-z]+$")){
                JOptionPane.showMessageDialog(this,
                        "Please Enter Valid Email Address",
                        "Invalid Email Address", 
                        JOptionPane.ERROR_MESSAGE);
            }
        
        else{
            if (evt.getSource() == addButton)
                    {
                        if(empDataObjs.size() > 0) {
                            for(EmployeeData e: empDataObjs) {
                                //e.getEid()
                                if(e.getEmployeeID().equals(eID)) {
                                    JOptionPane.showMessageDialog(this,
                            "Employee Data Already Exists!",
                            "Try Again", 
                            JOptionPane.ERROR_MESSAGE);
                                    break;
                                }
                                else {
                                    EmployeeData empData = new EmployeeData(eName, eID, age, empGender, startDate,
                                empLevel, empTeamInfo, empPT, empPhone, empEmail, imagePath);
                                    empDataObjs.add(empData);
                                    JOptionPane.showMessageDialog(this,
                            "Employee Data Saved",
                            "Done", 
                            JOptionPane.INFORMATION_MESSAGE);
                                }
                            }
                        }
                        else {
                                     EmployeeData empData = new EmployeeData(eName, eID, age, empGender, startDate,
                                empLevel, empTeamInfo, empPT, empPhone, empEmail, imagePath);
                                    empDataObjs.add(empData);
                                    JOptionPane.showMessageDialog(this,
                            "Employee Data Saved",
                            "Done", 
                            JOptionPane.INFORMATION_MESSAGE);
                                   
                                }
                        
                    }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void uploadPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadPhotoActionPerformed
            // TODO add your handling code here:
            JFileChooser uploadImage = new JFileChooser();
            uploadImage.setCurrentDirectory(new File("user.dir"));
            FileNameExtensionFilter imgExtensions = new FileNameExtensionFilter(" All Pic", "png", "jpeg","jpg","gif");
            uploadImage.addChoosableFileFilter(imgExtensions);
            int result = uploadImage.showSaveDialog(null);
            if(result == JFileChooser.APPROVE_OPTION){
                File selectFile = uploadImage.getSelectedFile();
            imagePath = selectFile.getAbsolutePath();
            ImageIcon chosenImage = new ImageIcon(imagePath);
            Image insertedImage = chosenImage.getImage().getScaledInstance(photoArea.getWidth(), 
                    photoArea.getHeight(), Image.SCALE_SMOOTH);
            photoArea.setIcon(new ImageIcon(insertedImage));
            }

            
    }//GEN-LAST:event_uploadPhotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageText;
    private javax.swing.JTextField cellPhoneText;
    private javax.swing.JPanel createEmployeePanel;
    private javax.swing.JLabel emailID;
    private javax.swing.JTextField emailIDText;
    private javax.swing.JLabel empIDLabel;
    private javax.swing.JTextField employeeIDText;
    private javax.swing.JRadioButton femaleInput;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jStartDate;
    private javax.swing.JTextField levelText;
    private javax.swing.JRadioButton maleInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JRadioButton otherInput;
    private javax.swing.JLabel photoArea;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JLabel positionTitle;
    private javax.swing.JTextField ptText;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JTextField teamInfoText;
    private javax.swing.JButton uploadPhoto;
    // End of variables declaration//GEN-END:variables
}
